### ISSUE TITLE
Missing value set EprDeletionStatus

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-epr-term#11]
A new value set has been created in the CH-EPR ArtDecor project: [EprDeletionStatus](https://art-decor.org/art-decor/decor-valuesets--ch-epr-?id=2.16.756.5.30.1.127.3.10.15.3), it's missing here.

**Comment by ziegm** [comment]
This is defined in CH EPR mHealth:
https://fhir.ch/ig/ch-epr-mhealth/CodeSystem-ch-ehealth-codesystem-deletionstatus.html

**Comment by qligier** [comment]
The value set is also used in XDS interfaces, it makes sense to move it from ch-epr-mhealth to ch-epr-term.

**Comment by oliveregger** [comment]
agree that we should move this to ch-epr-term

**Comment by oliveregger** [comment]
@qligier i exported it form art-decor (instead of just transferring), see above commit, can you check if would be ok like that?

**Comment by qligier** [comment]
It seems good to me, except for the escaped characters in the descriptions (nitpicking 😃)

**Comment by oliveregger** [comment]
fixed ...
