### ISSUE TITLE
The wrong version is taken

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-epr-term#14]
Art-Decor Changelog: https://ehealthsuisse.art-decor.org/ch-epr-html-20221201T141037/project.html
   * Two different versions of value set formatCode
      * DocumentEntry.formatCode (202212.0-Stable) => to publish
         * https://ehealthsuisse.art-decor.org/ch-epr-html-20221201T141037/voc-2.16.756.5.30.1.127.3.10.1.9-2022-07-20T193638.html 
      * DocumentEntry.formatCode (202404.0-beta) => at the moment this version is taken, see [PR](https://github.com/hl7ch/ch-epr-term/pull/13/files#diff-0d183aaef75f534866254cf902e69c015e02c36c4d85a1e7d4754bdb475a5dbb)
         * https://ehealthsuisse.art-decor.org/ch-epr-html-20221201T141037/voc-2.16.756.5.30.1.127.3.10.1.9-2022-11-30T144424.html

Current mechanism:
   * artdecor2ig\ch-epr-\build.xml
      * `<property name="version" value="20221201141037" />`

See also previous issue: https://github.com/hl7ch/ch-epr-term/issues/5

**Comment by oliveregger** [comment]
where there are valuesets with multiple versions in release the specific valueset version has to be defined manually in the ant build.xml script (currently only for DocumentEntry.formatCode).

**Comment by oliveregger** [comment]
see also issue #5
