### ISSUE TITLE
publication of a new version required

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-epr-term#17]
Updated DocumentEntry.typeCode (beta version), see https://github.com/hl7ch/ch-emed/issues/140#issuecomment-1529645749

**Comment by oliveregger** [comment]
we have to take issue #5 into consideration, till now ch-epr-term is only using stable versions

**Comment by ziegm** [comment]
Currently it isn't possible to have two versions of a value set in one version of an IG (see [zulip](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/2.20versions.20of.20a.20ValueSet.20in.201.20version.20of.20an.20IG))

**Comment by ziegm** [comment]
will fix it through relax the binding, because we are not able to have a beta and a stable version
https://github.com/hl7ch/ch-core/issues/215
