### ISSUE TITLE
Issue with the DocumentEntry.mimeType valueset

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-epr-term#21]
The valueset DocumentEntry.mimeType seems broken in the CI build: http://build.fhir.org/ig/hl7ch/ch-epr-term/ValueSet-DocumentEntry.mimeType.html
Comparing to v2.0.8: https://fhir.ch/ig/ch-epr-term/ValueSet-DocumentEntry.mimeType.html

- The Logical Definition is the same
- The Expansion now only contains 13 concepts, down from 25.
- In CH EPR mHealth, it triggers a warning: _Binding http://fhir.ch/ig/ch-epr-term/ValueSet/DocumentEntry.mimeType could not be expanded_. See https://github.com/ehealthsuisse/ch-epr-mhealth/issues/67

**Comment by oliveregger** [comment]
raised discussion on zulip: https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Expansion.20changed.20for.20v3-mediaType
