### ISSUE TITLE
List-Tags as plain text

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-epr-term#3]
include xthml in index.md shows list tags `</li>` as plain text, see [CI-Build](http://build.fhir.org/ig/hl7ch/ch-epr-term/branches/master/index.html)

File with following includes: input\pagecontent\index.md
- {% include list-simple-valuesets.xhtml %}
- {% include list-simple-codesystems.xhtml %}

the generated following raw xhtml has a correct syntax
- temp\pages\_includes\list-simple-valuesets.xhtml
- temp\pages\_includes\list-simple-codesystems.xhtml

**Comment by ziegm** [comment]
includes in Jekyll:
https://jekyllrb.com/docs/includes/

**Comment by oliveregger** [comment]
list items need to be in a list, eg <ul> ... </ul>
