### ISSUE TITLE
don't depend on ihe.formatcode.fhir#current

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-epr-term#9]
ihe.formatcode.fhir has been published and we should not depend on the ci-build version

**Comment by oliveregger** [comment]
https://profiles.ihe.net/fhir/ihe.formatcode.fhir/index.html

**Comment by ziegm** [comment]
this is fixed in the meantime
https://fhir.ch/ig/ch-epr-term/qa.html
https://github.com/hl7ch/ch-epr-term/blob/0c910038d86830c639f3a53ac33c7f2be7411844/input/ch.fhir.ig.ch-epr-term.xml#L41
